services:
  ylab:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ylab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: